DELIMITER $$
CREATE PROCEDURE INSERTAR_PRUEBA(CLAVE INT)
BEGIN
	DECLARE EXIT HANDLER 
		FOR SQLSTATE '23000'
	BEGIN
		SELECT 'ERROR: CLABE DUCPLICADA' AS MENSAJE;
        
    END;
    INSERT INTO PRUEBA(ID) VALUE(CLAVE);
    SELECT 'CLAVE CORRECTAMENTE AGREGADA' AS MENSAJE;
END$$


DELIMITER ;