DELIMITER $$
CREATE PROCEDURE INSERTAR_PRODUCTO(IN NOMBRE VARCHAR(40))
BEGIN
	DECLARE NUEVO_ID INT;
    SET NUEVO_ID = ULTIMO_ID() + 1;
    INSERT INTO PRODUCTOS VALUE(NUEVO_ID, NOMBRE);
END$$



DELIMITER ;