delimiter $$
CREATE FUNCTION AGREGAR_PAIS(ID VARCHAR(2), NOMBRE VARCHAR(40))
RETURNS INT DETERMINISTIC MODIFIES SQL DATA
BEGIN
	INSERT INTO COUNTRIES(COUNTRY_ID, COUNTRY_NAME, REGION_ID) value(ID, NOMBRE, 1);
    return 1;
END$$
delimiter ;